apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: roran
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/db: "true"
        io.kompose.service: app
    spec:
      containers:
        - args:
            - python3
            - bot.py
          env:
            - name: CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: CRYPTO_KEY
                  
            - name: CURRENCY_CONVERT
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: CURRENCY_CONVERT
                  
            - name: DISCORD_GUILD
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: DISCORD_GUILD

            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: DISCORD_TOKEN
                  
            - name: GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: GUILD_ID
                  
            - name: NEWS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: NEWS_API_KEY
                 
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: POSTGRES_DB
                  
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: POSTGRES_PASSWORD
                  
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: api-keys-7t4d7hc644
            - name: STOCK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: STOCK_API_KEY
                  
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: WEATHER_API_KEY
                  
            - name: YNAB_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys-7t4d7hc644
                  key: YNAB_KEY
                  
          image: roran:v3.30.53
          name: roran
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
      volumes:
        - name: app-claim1
          persistentVolumeClaim:
            claimName: app-claim1
status: {}
